favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.3853047
  brandStrength: 0
  lightness: 0.6020009
  brandColors:
    - '#898987'
    - '#BCBEBD'
    - '#151516'
    - '#319099'
    - '#F2EB7F'
  rhythmicContrast: 0.9186217
typography_spectrum: 0.5125448
layout_spectrum: 0.6774194
cta:
  bucket: null
  version: null
  domain: null
name: Munch inDesign
