purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.3817204
  brandStrength: 0.5151771
  rhythmicContrast: 1
  brandColors:
    - '#01040d'
    - '#f9fefa'
    - '#6fb7b3'
    - '#285e6a'
    - '#3d8b8d'
  lightness: 0.727656
analytics:
  twitter: null
  facebook: null
  google: null
favicon: null
cta:
  version: null
  bucket: null
  domain: null
name: Munch inDesign
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.07885305
layout_spectrum: 1
