layout_spectrum: 1
favicon: null
name: Munch inDesign
purpose: []
analytics:
  facebook: null
  google: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      paginate: true
      path: /
      number: 15
      navigable: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  version: null
  bucket: null
color:
  brandStrength: 0.5151771
  lightness: 0.727656
  saturation: 0.3817204
  rhythmicContrast: 1
  brandColors:
    - '#01040d'
    - '#f9fefa'
    - '#6fb7b3'
    - '#285e6a'
    - '#3d8b8d'
typography_spectrum: 0.7715008
