favicon: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
typography_spectrum: 0.60666
color:
  saturation: 0.3817204
  brandStrength: 0.2455197
  lightness: 0.4121864
  brandColors:
    - '#01040d'
    - '#f9fefa'
    - '#6fb7b3'
    - '#285e6a'
    - '#3d8b8d'
  rhythmicContrast: 1
cta:
  version: null
  bucket: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
layout_spectrum: 0.50894
name: Munch inDesign
