layout_spectrum: 0.50894
favicon: null
name: Munch inDesign
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      paginate: true
      path: /
      number: 15
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      format: rss
      path: /rss.xml
      number: 10
cta:
  version: null
  bucket: null
  domain: null
color:
  brandStrength: 0.5
  lightness: 0
  saturation: 0.3583474
  rhythmicContrast: 0.3701518
  brandColors:
    - '#01040d'
    - '#f9fefa'
    - '#6fb7b3'
    - '#285e6a'
    - '#3d8b8d'
typography_spectrum: 0.60666
